"""Terminal-to-pixel rendering with VT220 amber-tinted color scheme."""

import logging
import math
import shutil
import subprocess
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont
import pyte
import skia
import wcwidth

log = logging.getLogger(__name__)


# Per-theme 16-color ANSI palettes. Each palette is generated by
# ``oklch.generate_palette`` which picks colors at a constant
# perceived lightness (OKLCH L*) per hue — so every chromatic slot
# looks equally bright to the human eye, and every slot clears WCAG
# AA (4.5:1) contrast against the theme bg. The active palette is
# swapped in place by apply_theme().
from .oklch import generate_palette as _gen_palette

_DARK_BG = (0, 0, 0)
_LIGHT_BG = (255, 255, 255)
_NAVY_BG = (0x01, 0x24, 0x56)

# ---------------------------------------------------------------------------
# Phosphor palettes — single-hue per theme. Used by `phosphor` color
# mode (the default). Each palette has all 16 SGR slots but every slot
# is a *brightness* variant of the theme's primary hue — the SGR
# index becomes a luminance cue, not a chroma cue. This is the VT220
# / MDA aesthetic: everything is amber (or green, or grey, or cyan).
#
# Slot 0 ("black") is *near-bg* by design, so it legitimately fails
# the 3:1 contrast floor the other 15 slots clear. See design-color.md.
# ---------------------------------------------------------------------------

# Amber phosphor — preserved from the original vncvt release.
# Invariant: r >= g >= b (warmth).
_AMBER_PHOSPHOR = {
    "black":         (60, 40, 0),
    "red":           (255, 120, 60),
    "green":         (220, 200, 80),
    "brown":         (255, 220, 80),
    "blue":          (230, 180, 60),
    "magenta":       (255, 150, 100),
    "cyan":          (255, 210, 100),
    "white":         (255, 220, 140),
    "brightblack":   (180, 140, 60),
    "brightred":     (255, 160, 100),
    "brightgreen":   (255, 230, 120),
    "brightyellow":  (255, 240, 140),
    "brightblue":    (255, 200, 100),
    "brightmagenta": (255, 190, 140),
    "brightcyan":    (255, 230, 130),
    "brightwhite":   (255, 240, 180),
}

# Green phosphor — preserved. Invariant: g >= {r, b}.
_GREEN_PHOSPHOR = {
    "black":         (0, 30, 10),
    "red":           (180, 255, 180),
    "green":         (60, 255, 120),
    "brown":         (120, 255, 80),
    "blue":          (40, 200, 100),
    "magenta":       (200, 255, 160),
    "cyan":          (100, 255, 180),
    "white":         (200, 255, 200),
    "brightblack":   (40, 180, 90),
    "brightred":     (220, 255, 200),
    "brightgreen":   (160, 255, 200),
    "brightyellow":  (200, 255, 100),
    "brightblue":    (80, 240, 140),
    "brightmagenta": (220, 255, 200),
    "brightcyan":    (180, 255, 220),
    "brightwhite":   (255, 255, 220),
}

# Light phosphor — dark-grey ink-on-paper. Invariant: r == g == b.
# All slots clear WCAG 5:1+ on white bg.
_LIGHT_PHOSPHOR = {
    "black":         (0, 0, 0),
    "red":           (80, 80, 80),
    "green":         (70, 70, 70),
    "brown":         (60, 60, 60),
    "blue":          (50, 50, 50),
    "magenta":       (90, 90, 90),
    "cyan":          (75, 75, 75),
    "white":         (40, 40, 40),
    "brightblack":   (110, 110, 110),
    "brightred":     (65, 65, 65),
    "brightgreen":   (55, 55, 55),
    "brightyellow":  (45, 45, 45),
    "brightblue":    (35, 35, 35),
    "brightmagenta": (80, 80, 80),
    "brightcyan":    (60, 60, 60),
    "brightwhite":   (20, 20, 20),
}

# Dark phosphor — light-grey VT100 aesthetic. Invariant: r == g == b.
# Slot 0 (black) is near-bg by design; other 15 clear WCAG 6:1+.
_DARK_PHOSPHOR = {
    "black":         (20, 20, 20),
    "red":           (180, 180, 180),
    "green":         (190, 190, 190),
    "brown":         (200, 200, 200),
    "blue":          (210, 210, 210),
    "magenta":       (170, 170, 170),
    "cyan":          (185, 185, 185),
    "white":         (220, 220, 220),
    "brightblack":   (140, 140, 140),
    "brightred":     (200, 200, 200),
    "brightgreen":   (215, 215, 215),
    "brightyellow":  (225, 225, 225),
    "brightblue":    (230, 230, 230),
    "brightmagenta": (195, 195, 195),
    "brightcyan":    (210, 210, 210),
    "brightwhite":   (255, 255, 255),
}

# Powershell phosphor — cyan/blue family on navy #012456.
# Invariant: b >= g >= r (cool cast). Slot 0 is near-bg; other 15
# clear ~4.85:1+.
_POWERSHELL_PHOSPHOR = {
    "black":         (20, 55, 110),
    "red":           (140, 190, 225),
    "green":         (120, 175, 215),
    "brown":         (130, 185, 220),
    "blue":          (115, 170, 215),
    "magenta":       (150, 200, 230),
    "cyan":          (160, 205, 235),
    "white":         (200, 225, 245),
    "brightblack":   (100, 150, 200),
    "brightred":     (165, 210, 240),
    "brightgreen":   (175, 215, 240),
    "brightyellow":  (180, 220, 245),
    "brightblue":    (160, 210, 240),
    "brightmagenta": (190, 225, 250),
    "brightcyan":    (195, 230, 250),
    "brightwhite":   (225, 245, 255),
}

# ---------------------------------------------------------------------------
# CGA palettes — 16 distinct hues, theme-biased. Used by `16-color`
# and `256-color` color modes. OKLCH-generated at uniform perceived
# L*, with a ±30° hue rotation toward the theme's primary hue to
# give the palette a family resemblance.
# ---------------------------------------------------------------------------

# Neutral CGA bases (light/dark/powershell) — no hue bias; the theme
# bg picks "light" vs "dark" variant inside generate_palette.
_DARK_CGA = _gen_palette(_DARK_BG, base_l=0.78, bright_l=0.92, chroma=0.17)
_LIGHT_CGA = _gen_palette(_LIGHT_BG, base_l=0.40, bright_l=0.28, chroma=0.17)
_POWERSHELL_CGA = _gen_palette(
    _NAVY_BG, base_l=0.78, bright_l=0.92, chroma=0.17, hue_bias="cool",
)

# Amber/green CGA palettes keep 16 recognizably distinct hues but
# biased toward the theme's primary hue so they feel on-family.
_AMBER_CGA = _gen_palette(
    _DARK_BG, base_l=0.78, bright_l=0.92, chroma=0.13, hue_bias="warm",
)
_GREEN_CGA = _gen_palette(
    _DARK_BG, base_l=0.78, bright_l=0.92, chroma=0.13, hue_bias="green",
)

# Active palette — apply_theme() replaces this dict in place so any
# code holding a reference (including the 256-color builders below)
# sees the new colors. AMBER_COLORS is kept as a back-compat alias
# and points at the *phosphor* palette since that's the default mode.
AMBER_COLORS = dict(_AMBER_PHOSPHOR)

# pyte uses these names for the 8 basic colors
_PYTE_COLOR_NAMES = [
    "black", "red", "green", "brown", "blue", "magenta", "cyan", "white",
]

# Chars that should NEVER get an underline drawn under them, even if
# the cell has underscore=True. Covers ASCII space, NBSP, and the
# whole Unicode box-drawing block so separator rows don't produce a
# visible dark band.
_NO_UNDERLINE = frozenset(
    [" ", "\xa0"] + [chr(c) for c in range(0x2500, 0x2580)]
)

# Theme palettes. The active one is installed into the module-level
# DEFAULT_BG / DEFAULT_FG / BOLD_FG / CURSOR_COLOR constants by
# ``apply_theme()``; modules like test_padding.py that import
# DEFAULT_BG directly pick up whatever the current theme set.
THEMES: dict[str, dict] = {
    # Each theme has two 16-slot palettes: `ansi_phosphor` (single-hue
    # aesthetic for `phosphor` mode) and `ansi_cga` (theme-biased 16
    # distinct hues for `16-color` and `256-color` modes).
    "amber": {
        "bg":            (0, 0, 0),
        "fg":            (255, 190, 80),  # 12.73:1, warmer/orangy amber
        "bold":          (255, 220, 120), # ~14.5:1 peach-amber for bold
        "cursor":        (255, 190, 80),
        "ansi_phosphor": _AMBER_PHOSPHOR,
        "ansi_cga":      _AMBER_CGA,
    },
    "light": {  # black on white — 21.00:1 (WCAG max)
        "bg":            (255, 255, 255),
        "fg":            (0, 0, 0),
        "bold":          (0, 0, 0),
        "cursor":        (0, 0, 0),
        "ansi_phosphor": _LIGHT_PHOSPHOR,
        "ansi_cga":      _LIGHT_CGA,
    },
    "dark": {  # pure white on black — 21.00:1 (WCAG max)
        "bg":            (0, 0, 0),
        "fg":            (255, 255, 255),
        "bold":          (255, 255, 255),
        "cursor":        (255, 255, 255),
        "ansi_phosphor": _DARK_PHOSPHOR,
        "ansi_cga":      _DARK_CGA,
    },
    "green": {  # bright phosphor green — 16.31:1
        "bg":            (0, 0, 0),
        "fg":            (120, 255, 120),
        "bold":          (180, 255, 180),
        "cursor":        (120, 255, 120),
        "ansi_phosphor": _GREEN_PHOSPHOR,
        "ansi_cga":      _GREEN_CGA,
    },
    "powershell": {  # Windows PowerShell classic — 12.97:1
        "bg":            (0x01, 0x24, 0x56),  # #012456 dark navy
        "fg":            (0xEE, 0xED, 0xF0),  # #EEEDF0 off-white
        "bold":          (0xFF, 0xFF, 0xFF),  # pure white for bold
        "cursor":        (0xEE, 0xED, 0xF0),
        "ansi_phosphor": _POWERSHELL_PHOSPHOR,
        "ansi_cga":      _POWERSHELL_CGA,
    },
}

DEFAULT_BG = THEMES["amber"]["bg"]
DEFAULT_FG = THEMES["amber"]["fg"]
BOLD_FG = THEMES["amber"]["bold"]
CURSOR_COLOR = THEMES["amber"]["cursor"]


def apply_theme(name: str) -> None:
    """Install one of the THEMES palettes as the module-level defaults.

    Call before constructing any TerminalRenderer — the render path
    reads DEFAULT_BG / DEFAULT_FG / BOLD_FG / CURSOR_COLOR at draw
    time, so swapping them here is enough for a theme change. Three
    256-slot palette tables are rebuilt (phosphor, CGA, diminished)
    so _resolve_color can pick the right one based on color_mode.
    """
    if name not in THEMES:
        raise ValueError(
            f"unknown theme {name!r}; expected one of {sorted(THEMES)}"
        )
    global DEFAULT_BG, DEFAULT_FG, BOLD_FG, CURSOR_COLOR
    global _PALETTE_PHOSPHOR, _PALETTE_CGA, _PALETTE_256_DIMINISHED
    palette = THEMES[name]
    DEFAULT_BG = palette["bg"]
    DEFAULT_FG = palette["fg"]
    BOLD_FG = palette["bold"]
    CURSOR_COLOR = palette["cursor"]
    _PALETTE_PHOSPHOR = _build_256_from_ansi16(palette["ansi_phosphor"])
    _PALETTE_CGA = _build_256_from_ansi16(palette["ansi_cga"])
    _PALETTE_256_DIMINISHED = _build_256_diminished(
        palette["ansi_cga"], palette["bg"], palette["fg"],
    )
    # Back-compat: AMBER_COLORS used to hold the "current ANSI palette";
    # keep it pointing at the phosphor palette since phosphor is the
    # default color mode.
    AMBER_COLORS.clear()
    AMBER_COLORS.update(palette["ansi_phosphor"])

_VENDORED_FONT_DIR = Path(__file__).parent / "fonts"

FONT_SEARCH_PATHS = [
    # macOS: SF Mono Regular (system font). With Skia's subpixel AA
    # and LCD filtering, this matches what macOS Terminal.app renders.
    "/System/Library/Fonts/SFNSMono.ttf",
    # macOS fallback
    "/System/Library/Fonts/Menlo.ttc",
    # Linux fallbacks
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf",
    "/usr/share/fonts/truetype/freefont/FreeMono.ttf",
    "/usr/share/fonts/TTF/DejaVuSansMono.ttf",
    "/usr/share/fonts/dejavu-sans-mono-fonts/DejaVuSansMono.ttf",
    # Vendored Terminus TTF is kept as the ultimate fallback for
    # environments without any monospace font installed.
    str(_VENDORED_FONT_DIR / "TerminusTTF-4.49.3.ttf"),
]

BOLD_FONT_SEARCH_PATHS = [
    "/System/Library/Fonts/SFNSMono.ttf",  # has an embedded Bold face
    "/System/Library/Fonts/Menlo.ttc",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf",
    "/usr/share/fonts/truetype/freefont/FreeMonoBold.ttf",
    "/usr/share/fonts/TTF/DejaVuSansMono-Bold.ttf",
    str(_VENDORED_FONT_DIR / "TerminusTTF-Bold-4.49.3.ttf"),
]


def _find_font(paths: list[str]) -> str | None:
    for path in paths:
        if Path(path).exists():
            return path
    if shutil.which("fc-match"):
        try:
            out = subprocess.check_output(
                ["fc-match", "-f", "%{file}", "monospace"], text=True
            ).strip()
            if Path(out).exists():
                return out
        except subprocess.SubprocessError:
            pass
    return None


# 256-color palette builders. Three tables get built per theme:
#
#   _PALETTE_PHOSPHOR       — ANSI 0-15 = theme's phosphor dict,
#                             cube 16-231 and grey 232-255 built from
#                             the same hand-tuned dict so everything
#                             stays single-hue (for `phosphor` mode).
#   _PALETTE_CGA            — ANSI 0-15 = theme's CGA dict, cube and
#                             grey built from it (for `16-color`
#                             integer-index lookups, where the user
#                             asked for 16 distinct hues).
#   _PALETTE_256_DIMINISHED — ANSI 0-15 from CGA dict; cube 16-231 is
#                             xterm 6x6x6 desaturated 40% toward the
#                             theme's bg/fg midpoint; grey 232-255
#                             interpolates along the bg→fg OKLab axis
#                             (for `256-color` mode — see design doc).
_BRIGHT_MAP = {
    "black": "brightblack", "red": "brightred", "green": "brightgreen",
    "brown": "brightyellow", "blue": "brightblue", "magenta": "brightmagenta",
    "cyan": "brightcyan", "white": "brightwhite",
}


def _build_256_from_ansi16(
    ansi16: dict[str, tuple[int, int, int]],
) -> list[tuple[int, int, int]]:
    """Build a 256-slot palette from a 16-slot SGR dict.

    Slots 0-15 come from the dict verbatim; slots 16-231 are the
    xterm 6x6x6 cube blended 60/40 toward the dict's white entry so
    it stays on-theme; slots 232-255 are a grey ramp interpolated
    between the dict's black and white slots.
    """
    palette: list[tuple[int, int, int]] = []
    for name in _PYTE_COLOR_NAMES:
        palette.append(ansi16[name])
    for name in _PYTE_COLOR_NAMES:
        palette.append(ansi16[_BRIGHT_MAP[name]])
    tint = ansi16["white"]
    levels = [0, 0x5f, 0x87, 0xaf, 0xd7, 0xff]
    for r in levels:
        for g in levels:
            for b in levels:
                # Mix each cube entry toward the theme's peak hue so
                # the result stays inside the theme family. 60/40 is
                # the same ratio used by `_build_256_diminished`.
                cr = int(r * 0.6 + tint[0] * 0.4)
                cg = int(g * 0.6 + tint[1] * 0.4)
                cb = int(b * 0.6 + tint[2] * 0.4)
                palette.append((
                    max(0, min(255, cr)),
                    max(0, min(255, cg)),
                    max(0, min(255, cb)),
                ))
    black = ansi16["black"]
    white = ansi16["brightwhite"]
    for i in range(24):
        t = i / 23.0
        palette.append((
            int(black[0] + (white[0] - black[0]) * t),
            int(black[1] + (white[1] - black[1]) * t),
            int(black[2] + (white[2] - black[2]) * t),
        ))
    return palette


def _build_256_diminished(
    ansi16: dict[str, tuple[int, int, int]],
    bg: tuple[int, int, int],
    fg: tuple[int, int, int],
) -> list[tuple[int, int, int]]:
    """Build the `256-color` tier palette: CGA ANSI 0-15, a desaturated
    xterm cube 16-231 (60/40 blend toward the bg/fg midpoint), and a
    greyscale ramp 232-255 interpolated along the bg→fg OKLab L* axis.

    See design-color.md — this is the "VGA Mode 13h" tier: more
    gradation than CGA, less chroma than truecolor, still on-theme.
    """
    from .oklch import oklab_to_srgb, srgb_to_oklab

    palette: list[tuple[int, int, int]] = []
    # 0-15: CGA slots verbatim.
    for name in _PYTE_COLOR_NAMES:
        palette.append(ansi16[name])
    for name in _PYTE_COLOR_NAMES:
        palette.append(ansi16[_BRIGHT_MAP[name]])
    # 16-231: xterm cube desaturated 40% toward the bg/fg midpoint.
    mid = (
        (bg[0] + fg[0]) // 2,
        (bg[1] + fg[1]) // 2,
        (bg[2] + fg[2]) // 2,
    )
    levels = [0, 0x5f, 0x87, 0xaf, 0xd7, 0xff]
    for r in levels:
        for g in levels:
            for b in levels:
                cr = int(r * 0.6 + mid[0] * 0.4)
                cg = int(g * 0.6 + mid[1] * 0.4)
                cb = int(b * 0.6 + mid[2] * 0.4)
                palette.append((
                    max(0, min(255, cr)),
                    max(0, min(255, cg)),
                    max(0, min(255, cb)),
                ))
    # 232-255: 24-step grey ramp along the bg→fg OKLab L* axis.
    bg_L, bg_a, bg_b = srgb_to_oklab(*bg)
    fg_L, fg_a, fg_b = srgb_to_oklab(*fg)
    for i in range(24):
        t = i / 23.0
        L = bg_L + (fg_L - bg_L) * t
        a = bg_a + (fg_a - bg_a) * t
        bb = bg_b + (fg_b - bg_b) * t
        palette.append(oklab_to_srgb(L, a, bb))
    return palette


# Module-level palette tables. apply_theme() rebuilds these whenever
# the theme changes.
_PALETTE_PHOSPHOR = _build_256_from_ansi16(_AMBER_PHOSPHOR)
_PALETTE_CGA = _build_256_from_ansi16(_AMBER_CGA)
_PALETTE_256_DIMINISHED = _build_256_diminished(
    _AMBER_CGA, (0, 0, 0), (255, 190, 80),
)


# Standard xterm 256-color palette — NOT theme-tinted. Used by
# true-color mode so TUIs emitting ANSI indices render in their
# native xterm colors instead of the theme's OKLCH palette.
_STANDARD_ANSI_16 = [
    (0, 0, 0), (205, 0, 0), (0, 205, 0), (205, 205, 0),
    (0, 0, 238), (205, 0, 205), (0, 205, 205), (229, 229, 229),
    (127, 127, 127), (255, 0, 0), (0, 255, 0), (255, 255, 0),
    (92, 92, 255), (255, 0, 255), (0, 255, 255), (255, 255, 255),
]


def _build_standard_256() -> list[tuple[int, int, int]]:
    palette = list(_STANDARD_ANSI_16)
    levels = [0, 95, 135, 175, 215, 255]
    for r in levels:
        for g in levels:
            for b in levels:
                palette.append((r, g, b))
    for i in range(24):
        v = 8 + i * 10
        palette.append((v, v, v))
    return palette


_STANDARD_PALETTE_256 = _build_standard_256()


def _snap_to_palette(
    rgb: tuple[int, int, int],
    palette: list[tuple[int, int, int]] | tuple[tuple[int, int, int], ...],
) -> tuple[int, int, int]:
    """Return the palette entry with minimum squared-RGB distance
    from ``rgb``. Used by 16-color mode to quantize truecolor
    inputs down to the theme's ANSI 16."""
    best = palette[0]
    best_d = float("inf")
    for entry in palette:
        d = (
            (rgb[0] - entry[0]) ** 2
            + (rgb[1] - entry[1]) ** 2
            + (rgb[2] - entry[2]) ** 2
        )
        if d < best_d:
            best_d = d
            best = entry
    return best


def _wcag_contrast(
    fg: tuple[int, int, int], bg: tuple[int, int, int],
) -> float:
    """WCAG 2.1 contrast ratio. Used to keep 16-color fg snaps
    readable against the cell bg they'll be rendered on."""
    def srgb_to_linear(c: float) -> float:
        return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4

    def luminance(rgb):
        return (
            0.2126 * srgb_to_linear(rgb[0] / 255.0)
            + 0.7152 * srgb_to_linear(rgb[1] / 255.0)
            + 0.0722 * srgb_to_linear(rgb[2] / 255.0)
        )

    l1, l2 = luminance(fg), luminance(bg)
    return (max(l1, l2) + 0.05) / (min(l1, l2) + 0.05)


def _snap_to_palette_readable(
    rgb: tuple[int, int, int],
    palette: list[tuple[int, int, int]] | tuple[tuple[int, int, int], ...],
    cell_bg: tuple[int, int, int] | None,
    min_ratio: float = 3.0,
) -> tuple[int, int, int]:
    """Nearest-RGB snap, but constrained to palette entries that
    clear ``min_ratio`` WCAG contrast against ``cell_bg``. Falls
    back to the highest-contrast entry if none qualify — that way
    the chunky 16-color aesthetic stays readable.

    ``cell_bg`` unknown → falls through to plain ``_snap_to_palette``.
    """
    if cell_bg is None:
        return _snap_to_palette(rgb, palette)
    readable = [e for e in palette if _wcag_contrast(e, cell_bg) >= min_ratio]
    if readable:
        return _snap_to_palette(rgb, readable)
    # No palette entry is readable on this bg — pick the one with
    # maximum contrast as a last resort.
    return max(palette, key=lambda e: _wcag_contrast(e, cell_bg))


def _cell_in_selection(
    col: int,
    row: int,
    sel: tuple[tuple[int, int], tuple[int, int]] | None,
) -> bool:
    """Return True if (col, row) lies within the normalized selection."""
    if sel is None:
        return False
    (sc, sr), (ec, er) = sel
    if row < sr or row > er:
        return False
    if row == sr and row == er:
        return sc <= col <= ec
    if row == sr:
        return col >= sc
    if row == er:
        return col <= ec
    return True


class TerminalRenderer:
    """Renders a pyte Screen to an RGBX pixel buffer with amber-tinted colors."""

    # Overscan compensation: extra pixels of background around the
    # cell grid, like a CRT's overscan region. Mostly cosmetic — it
    # keeps the first column of text from hugging the screen edge.
    PADDING = 5

    def __init__(
        self,
        cols: int = 80,
        rows: int = 24,
        font_path: str | None = None,
        font_size: int = 16,
        line_height: float = 1.0,
        contrast: str = "normal",
        color_mode: str = "phosphor",
    ):
        self.cols = cols
        self.rows = rows
        self.padding = self.PADDING
        self.contrast = contrast
        self.color_mode = color_mode
        self.line_height = line_height

        # Load fonts
        if font_path is None:
            font_path = _find_font(FONT_SEARCH_PATHS)
        if font_path is None:
            raise RuntimeError(
                "No monospace font found. Install dejavu-sans-mono or use --font."
            )
        # Stash resolved font path + size so Phase 2 SET-UP mode can
        # rebuild this renderer without guessing (Pillow's ImageFont
        # doesn't expose the path portably across versions).
        self._font_path = font_path
        self.font_size = font_size
        self.font = ImageFont.truetype(font_path, font_size)

        bold_path = _find_font(BOLD_FONT_SEARCH_PATHS)
        self.font_bold = (
            ImageFont.truetype(bold_path, font_size) if bold_path else self.font
        )

        # Skia fonts for actual glyph rasterization. Pillow's fonts
        # above are kept for getlength() / getmetrics() measurement
        # only — Skia does the drawing so we get subpixel positioning,
        # LCD filtering, and stem darkening that Pillow+FreeType doesn't
        # expose.
        self._skia_typeface = skia.Typeface.MakeFromFile(font_path)
        self._skia_typeface_bold = (
            skia.Typeface.MakeFromFile(bold_path) if bold_path
            else self._skia_typeface
        )
        self._skia_font = skia.Font(self._skia_typeface, font_size)
        self._skia_font_bold = skia.Font(self._skia_typeface_bold, font_size)

        # Font fallback chain. When a codepoint's glyph is missing from
        # the primary typeface (Hangul / CJK / emoji), we walk this list
        # and pick the first entry whose unicharToGlyph returns non-zero.
        # Order matters: we want SF Mono (or whatever --font was set)
        # to win for Latin, Sarasa Mono K for CJK, and Apple Color
        # Emoji for pictographic codepoints.
        self._skia_fallback_fonts: list[skia.Font] = [self._skia_font]
        self._skia_fallback_fonts_bold: list[skia.Font] = [self._skia_font_bold]
        # Per-font "is color bitmap" flag so _draw_glyph can avoid
        # tinting emoji via Paint.setColor.
        self._skia_fallback_is_color: list[bool] = [False]
        self._skia_fallback_is_color_bold: list[bool] = [False]

        sarasa_reg = _VENDORED_FONT_DIR / "SarasaMonoK-Regular.ttf"
        sarasa_bold = _VENDORED_FONT_DIR / "SarasaMonoK-Bold.ttf"
        if sarasa_reg.is_file():
            tf = skia.Typeface.MakeFromFile(str(sarasa_reg))
            if tf is not None:
                self._skia_fallback_fonts.append(skia.Font(tf, font_size))
                self._skia_fallback_is_color.append(False)
        if sarasa_bold.is_file():
            tf = skia.Typeface.MakeFromFile(str(sarasa_bold))
            if tf is not None:
                self._skia_fallback_fonts_bold.append(skia.Font(tf, font_size))
                self._skia_fallback_is_color_bold.append(False)

        apple_emoji = Path("/System/Library/Fonts/Apple Color Emoji.ttc")
        if apple_emoji.is_file():
            tf = skia.Typeface.MakeFromFile(str(apple_emoji))
            if tf is not None:
                emoji_font = skia.Font(tf, font_size)
                self._skia_fallback_fonts.append(emoji_font)
                self._skia_fallback_is_color.append(True)
                # Bold reuses the same emoji font — color emoji has no
                # weight axis.
                self._skia_fallback_fonts_bold.append(emoji_font)
                self._skia_fallback_is_color_bold.append(True)

        # Apply shared rasterization flags to every fallback font.
        for f in (
            *self._skia_fallback_fonts,
            *self._skia_fallback_fonts_bold,
        ):
            f.setSubpixel(True)
            # Grayscale AA (not LCD subpixel) — amber-on-black has no
            # blue channel transition, so subpixel rendering produces
            # red/green fringes that hurt perceived crispness. Plain
            # gray AA stays out of the way.
            f.setEdging(skia.Font.Edging.kAntiAlias)
            # In high-contrast mode, drop hinting to kNone so glyph
            # outlines are rasterized without pixel-snap; the resulting
            # strokes are thicker (1.5-2 px wide instead of hard-snapped
            # 1 px) and look noticeably brighter at small sizes.
            f.setHinting(
                skia.FontHinting.kNone if contrast == "high"
                else skia.FontHinting.kFull
            )
            # Let SF Mono's native TrueType hints drive — they're
            # hand-tuned by Apple and beat Skia's autohinter.
            f.setForceAutoHinting(False)
            f.setLinearMetrics(False)
            f.setBaselineSnap(True)

        # Baseline offset: Pillow's draw.text anchors glyphs at the
        # top-left; Skia's drawString anchors at the baseline. Stash
        # the font's ascent so the call site can pass the baseline
        # y-coordinate.
        skia_metrics = self._skia_font.getMetrics()
        self._skia_baseline = -skia_metrics.fAscent

        # Measure character cell using advance width, not ink bbox.
        # getlength() returns the horizontal advance — the correct metric for
        # grid layout in a monospace font. Use math.ceil so we always
        # round UP; int(round()) can undersize the cell by ~0.5 px for
        # fonts whose advance is fractional (SF Mono at 13pt → 7.8,
        # rounded to 8, which leaves a sub-pixel gap every ~6 glyphs).
        self.cell_width = math.ceil(self.font.getlength("M"))
        ascent, descent = self.font.getmetrics()
        font_cell_h = ascent + descent
        self.cell_height = max(1, math.ceil(font_cell_h * self.line_height))
        self._x_offset = 0
        # Vertically center the glyph inside the expanded cell when
        # line_height > 1.0 so the extra space is shared above/below.
        self._y_offset = (self.cell_height - font_cell_h) // 2
        self._skia_baseline += self._y_offset

        # Warn if bold font has a different advance (would cause grid drift).
        if self.font_bold is not self.font:
            bold_adv = int(round(self.font_bold.getlength("M")))
            if bold_adv != self.cell_width:
                log.warning(
                    "Bold font advance (%d) != regular (%d); bold glyphs "
                    "will be clipped to the regular cell width",
                    bold_adv, self.cell_width,
                )

        self.width = cols * self.cell_width + 2 * self.padding
        self.height = rows * self.cell_height + 2 * self.padding

        # Create framebuffer image (padded by DEFAULT_BG on all sides).
        self.image = Image.new("RGBX", (self.width, self.height), DEFAULT_BG)
        self._prev_cursor = (-1, -1)

    def _find_font_for_char(
        self, ch: str, bold: bool,
    ) -> tuple["skia.Font", bool]:
        """Pick the first fallback font that has a glyph for ``ch``.

        Returns ``(font, is_color)`` where is_color signals that the
        font renders via color bitmaps (Apple Color Emoji) and the
        caller must not apply a Paint color — that would tint the
        sbix bitmap.
        """
        if bold:
            fonts = self._skia_fallback_fonts_bold
            color_flags = self._skia_fallback_is_color_bold
        else:
            fonts = self._skia_fallback_fonts
            color_flags = self._skia_fallback_is_color
        code = ord(ch[0])
        for font, is_color in zip(fonts, color_flags):
            if font.unicharToGlyph(code):
                return font, is_color
        # Fall back to the primary so the renderer at least draws
        # .notdef instead of silently skipping.
        return fonts[0], color_flags[0]

    def _draw_glyph(
        self,
        ch: str,
        bold: bool,
        x: int,
        y: int,
        fg: tuple[int, int, int],
        bg: tuple[int, int, int],
        cell_w: int,
    ) -> None:
        """Rasterize one glyph via Skia and paste into self.image.

        Skia gives us subpixel positioning, LCD filtering, and stem
        darkening that Pillow+FreeType doesn't expose. The tradeoff
        is one tiny offscreen surface per glyph — acceptable for
        dirty-row rendering at ~80 chars/row × 30 rows.
        """
        w = cell_w
        h = self.cell_height
        surface = skia.Surface.MakeRasterN32Premul(w, h)
        canvas = surface.getCanvas()
        canvas.clear(skia.ColorSetRGB(*bg))
        font, is_color = self._find_font_for_char(ch, bold=bold)
        paint = skia.Paint(AntiAlias=True)
        if not is_color:
            # Color-bitmap fonts (Apple Color Emoji) carry their own
            # sbix pixels. Applying Paint.setColor would tint the
            # bitmap to the fg color, destroying the emoji art.
            paint.setColor(skia.ColorSetRGB(*fg))
        canvas.drawString(ch, 0, self._skia_baseline, font, paint)
        if not is_color:
            # Embolden via repeated draws at sub-pixel offsets.
            # Each extra draw thickens strokes without the jaggies of
            # 1-bit AA. Skipped for color bitmap emoji (would smear
            # the sbix bitmap).
            if self.contrast == "high":
                # +1 horizontal draw → strokes are ~1.5-2 px wide
                canvas.drawString(ch, 1, self._skia_baseline, font, paint)
            elif self.contrast == "max":
                # Horizontal + diagonal half-step → thicker than
                # "high" without the blocky smear of a 4-corner
                # draw. Keeps curve outlines smooth.
                canvas.drawString(ch, 1, self._skia_baseline, font, paint)
                canvas.drawString(
                    ch, 0.5, self._skia_baseline + 0.5, font, paint,
                )
        # Snapshot -> RGBA bytes -> paste into self.image.
        # skia N32Premul is BGRA on little-endian Apple silicon; use
        # encodeToData(PNG) if byte-order matters, but for speed we
        # use peekPixels and swizzle.
        img_info = skia.ImageInfo.MakeN32Premul(w, h)
        buf = bytearray(w * h * 4)
        surface.readPixels(img_info, buf, w * 4, 0, 0)
        # Skia's N32 is RGBA_8888 on macOS arm64 (and RGBA by default
        # on most modern builds), so no byte swizzle needed.
        tile = Image.frombytes("RGBA", (w, h), bytes(buf))
        self.image.paste(tile, (x, y))

    def resize(self, cols: int, rows: int) -> None:
        """Resize the framebuffer to new terminal dimensions."""
        self.cols = cols
        self.rows = rows
        self.width = cols * self.cell_width + 2 * self.padding
        self.height = rows * self.cell_height + 2 * self.padding
        self.image = Image.new("RGBX", (self.width, self.height), DEFAULT_BG)
        self._prev_cursor = (-1, -1)

    def _resolve_color(
        self,
        color: str,
        bold: bool = False,
        is_bg: bool = False,
        cell_bg: tuple[int, int, int] | None = None,
    ) -> tuple[int, int, int]:
        """Map a pyte color value to an amber-tinted RGB tuple."""
        if color == "default" or color is None:
            if is_bg:
                return DEFAULT_BG
            return BOLD_FG if bold else DEFAULT_FG

        # Named color
        if color in AMBER_COLORS:
            if bold and not is_bg and not color.startswith("bright"):
                # "brown" promotes to "brightyellow" per standard ANSI
                bright_name = "brightyellow" if color == "brown" else ("bright" + color)
                if bright_name in AMBER_COLORS:
                    return AMBER_COLORS[bright_name]
            return AMBER_COLORS[color]

        # Integer index (256-color)
        if isinstance(color, int) or (
            isinstance(color, str) and len(color) <= 3 and color.isdigit()
        ):
            idx = int(color)
            if 0 <= idx < 256:
                if self.color_mode == "phosphor":
                    # Single-hue theme ramp: every SGR index collapses
                    # to a brightness variant of the theme hue.
                    return _PALETTE_PHOSPHOR[idx]
                if self.color_mode == "16-color":
                    wrapped = _PALETTE_CGA[idx % 16]
                    if is_bg or cell_bg is None:
                        return wrapped
                    if _wcag_contrast(wrapped, cell_bg) >= 3.0:
                        return wrapped
                    # fg: fall back to the 16-color CGA palette
                    # extended with the theme fg/bg poles so a
                    # readable option always exists.
                    return _snap_to_palette_readable(
                        wrapped,
                        list(_PALETTE_CGA[:16]) + [DEFAULT_FG, DEFAULT_BG],
                        cell_bg,
                    )
                if self.color_mode == "true-color":
                    return _STANDARD_PALETTE_256[idx]
                # default "256-color": theme's diminished VGA palette
                return _PALETTE_256_DIMINISHED[idx]

        # 6-char hex string (truecolor). We route it through the
        # current theme's DEFAULT_BG → DEFAULT_FG ramp using
        # *perceptual* OKLab L* instead of Rec-601 RGB luminance.
        # A gamma lift (t = L**0.4) pushes midtone greys aggressively
        # toward fg so Claude Code's "hint grey" (#808080-ish) reads
        # at WCAG AA or better instead of the ~3:1 linear-ramp
        # produced. Without the lift, #949494 on a white bg mapped
        # to (107, 107, 107) → 3.1:1 (fail); with it, (44, 44, 44)
        # → 7.4:1 (AAA).
        if isinstance(color, str) and len(color) == 6:
            try:
                r = int(color[0:2], 16)
                g = int(color[2:4], 16)
                b = int(color[4:6], 16)
                raw_rgb = (r, g, b)
                ramp_rgb = self._apply_oklab_ramp(
                    r, g, b, is_bg=is_bg, cell_bg=cell_bg,
                )
                if self.color_mode == "phosphor":
                    # Collapse to the theme's single-hue ramp.
                    return ramp_rgb
                if self.color_mode == "16-color":
                    if is_bg:
                        return _snap_to_palette(raw_rgb, _PALETTE_CGA[:16])
                    return _snap_to_palette_readable(
                        raw_rgb,
                        list(_PALETTE_CGA[:16]) + [DEFAULT_FG, DEFAULT_BG],
                        cell_bg,
                    )
                if self.color_mode == "true-color":
                    # fg keeps lift (else Claude dim-grey fg becomes
                    # invisible); bg passes through raw.
                    return raw_rgb if is_bg else ramp_rgb
                # default "256-color": bg → theme ramp; fg → theme ramp.
                return ramp_rgb
            except ValueError:
                pass

        return DEFAULT_FG

    def _apply_oklab_ramp(
        self,
        r: int,
        g: int,
        b: int,
        is_bg: bool,
        cell_bg: tuple[int, int, int] | None,
    ) -> tuple[int, int, int]:
        """Map a raw truecolor input onto the theme's bg→fg OKLab ramp.

        Returns the ramp-mapped RGB regardless of mode; callers decide
        whether to use it raw, blended, or as a full replacement.

        Preserves the orientation flip, cell_bg-aware reference frame,
        L_eff floor, and gamma 0.4 lift introduced earlier so Claude
        Code's mid-grey hint colors clear WCAG AA on every theme.
        """
        from .oklch import srgb_to_oklab
        L, _, _ = srgb_to_oklab(r, g, b)
        # Choose the lift's reference frame. If the caller told us the
        # cell's actual bg (via cell_bg), use that — fg should always be
        # pushed *away* from the bg it will be painted against,
        # regardless of theme defaults. Falling back to DEFAULT_BG /
        # DEFAULT_FG when cell_bg is unknown preserves legacy behavior.
        if cell_bg is not None:
            bg_L, _, _ = srgb_to_oklab(*cell_bg)
            if bg_L >= 0.5:
                # Light cell bg: push fg toward black so the darkest
                # input intent (L=0) lands on black.
                ref_bg = (255, 255, 255)
                ref_fg = (0, 0, 0)
            else:
                ref_bg = (0, 0, 0)
                ref_fg = (255, 255, 255)
            ref_bg_L = 1.0 if bg_L >= 0.5 else 0.0
            ref_fg_L = 0.0 if bg_L >= 0.5 else 1.0
        else:
            ref_bg = DEFAULT_BG
            ref_fg = DEFAULT_FG
            ref_bg_L, _, _ = srgb_to_oklab(*DEFAULT_BG)
            ref_fg_L, _, _ = srgb_to_oklab(*DEFAULT_FG)
        # The lift parameterizes the input on a bg→fg perceptual ramp.
        # On dark-on-light orientations (ref_bg brighter than ref_fg),
        # L=0 is the user's darkest intent and should map to ref_fg
        # (black), not ref_bg (white). Flip the parameter so the ramp
        # always goes "user intent low → bg, user intent high → fg"
        # relative to the chosen orientation.
        L_eff = L if ref_fg_L >= ref_bg_L else (1.0 - L)
        # Floor L_eff so an input that lands on (or very near) the bg
        # pole still gets enough lift to escape it. Rescues the
        # "fg=#000000 on a dark cell bg" case where the user's literal
        # intent is invisible — we honor the neutrality (still grey)
        # but force enough delta from the bg to clear ~9:1.
        L_eff = max(L_eff, 0.5)
        # Clamp L into [0, 1] then apply gamma lift. The 0.4 exponent
        # was tuned against Claude Code's actual grey inputs (#808080,
        # #949494, #d78787) to clear 4.5:1 on every built-in theme bg.
        t = max(0.0, min(1.0, L_eff)) ** 0.4
        bg_r, bg_g, bg_b = ref_bg
        fg_r, fg_g, fg_b = ref_fg
        return (
            int(bg_r + (fg_r - bg_r) * t),
            int(bg_g + (fg_g - bg_g) * t),
            int(bg_b + (fg_b - bg_b) * t),
        )

    def render_dirty(
        self,
        screen: pyte.Screen,
        dirty_rows: set[int],
        selection: tuple[tuple[int, int], tuple[int, int]] | None = None,
    ) -> list[tuple[int, int, int, int, "Image.Image"]]:
        """Re-render dirty rows. Returns list of (x, y, w, h, PIL.Image) rectangles.

        If `selection` is given as ``((start_col, start_row), (end_col, end_row))``
        in reading order, cells inside the range are drawn with inverted
        foreground/background colors to indicate highlight.
        """
        if not dirty_rows:
            return []

        draw = ImageDraw.Draw(self.image)
        rects = []

        pad = self.padding
        inner_w = self.cols * self.cell_width

        for row in sorted(dirty_rows):
            if row >= self.rows:
                continue
            y = row * self.cell_height + pad

            # Clear the cell-grid area for this row (leave side padding alone).
            draw.rectangle(
                [pad, y, pad + inner_w - 1, y + self.cell_height - 1],
                fill=DEFAULT_BG,
            )

            line = screen.buffer[row]
            skip_next = 0
            for col in range(self.cols):
                if skip_next:
                    skip_next -= 1
                    continue

                char = line[col]
                x = col * self.cell_width + pad
                ch = char.data

                bg = self._resolve_color(char.bg, False, is_bg=True)
                fg = self._resolve_color(
                    char.fg, char.bold, is_bg=False, cell_bg=bg,
                )

                if char.reverse:
                    fg, bg = bg, fg

                # Selection highlight: invert after reverse handling so a
                # reverse-video cell inside a selection returns to normal.
                if _cell_in_selection(col, row, selection):
                    fg, bg = bg, fg

                # Determine cell span via wcwidth.
                #   2  -> double-wide (CJK, some emoji)
                #   1  -> normal
                #   0  -> combining mark (overlay onto previous cell)
                #  -1  -> control/unassigned (treat as 1)
                w = wcwidth.wcwidth(ch) if ch else 1
                cells = 2 if w == 2 else 1
                cell_px = self.cell_width * cells

                # Combining mark: overlay on previous cell. For now
                # we just draw it over the previous cell's bg — Skia
                # doesn't support stacking marks trivially. Acceptable
                # since combining marks are rare in terminal output.
                if w == 0 and col > 0 and ch:
                    prev_x = (col - 1) * self.cell_width + pad
                    self._draw_glyph(
                        ch, char.bold, prev_x, y, fg, DEFAULT_BG,
                        self.cell_width,
                    )
                    continue

                # Draw the cell: background + glyph in one Skia pass.
                # _draw_glyph fills bg first then draws the glyph, so
                # we don't need a separate rectangle clear.
                if ch and ch != " ":
                    self._draw_glyph(
                        ch, char.bold, x, y, fg, bg, cell_px,
                    )
                elif bg != DEFAULT_BG:
                    # Empty cell with a non-default background.
                    draw.rectangle(
                        [x, y, x + cell_px - 1, y + self.cell_height - 1],
                        fill=bg,
                    )

                # Underline — skip on whitespace and box-drawing cells.
                # Claude Code (and some other TUIs) set the underscore
                # attribute on whole rows of separator characters
                # (`─`, spaces). Rendering a full-width underline bar
                # under those produces a visible dark horizontal valley.
                # For real text (URLs, prompts) the underline is still
                # drawn in the cell's fg color.
                if char.underscore and ch and ch not in _NO_UNDERLINE:
                    ul_y = y + self.cell_height - 2
                    draw.line(
                        [x, ul_y, x + cell_px - 1, ul_y], fill=fg,
                    )

                if cells == 2:
                    skip_next = 1

            # Return a crop view of the row (inner area only). Skipping
            # the side padding saves a few bytes per row and keeps the
            # update bounded to cells that actually changed.
            row_img = self.image.crop(
                (pad, y, pad + inner_w, y + self.cell_height)
            )
            rects.append((pad, y, inner_w, self.cell_height, row_img))

        return rects

    def render_cursor(
        self, screen: pyte.Screen
    ) -> tuple[int, int, int, int, "Image.Image"] | None:
        """Render cursor block. Returns (x, y, w, h, PIL.Image) or None."""
        cx, cy = screen.cursor.x, screen.cursor.y
        if cx >= self.cols or cy >= self.rows:
            return None

        char = screen.buffer[cy][cx]
        ch = char.data
        w = wcwidth.wcwidth(ch) if ch else 1
        cells = 2 if w == 2 else 1
        cell_px = self.cell_width * cells

        x = cx * self.cell_width + self.padding
        y = cy * self.cell_height + self.padding

        # Draw cursor as a filled block with inverted colors.
        cursor_img = self.image.crop(
            (x, y, x + cell_px, y + self.cell_height)
        ).copy()
        draw = ImageDraw.Draw(cursor_img)
        draw.rectangle(
            [0, 0, cell_px - 1, self.cell_height - 1],
            fill=CURSOR_COLOR,
        )

        # Redraw character under cursor with inverted color.
        if ch and ch != " ":
            draw.text(
                (self._x_offset, self._y_offset),
                ch, font=self.font, fill=DEFAULT_BG,
            )

        self._prev_cursor = (cx, cy)
        return (x, y, cell_px, self.cell_height, cursor_img)

    def full_render(
        self,
        screen: pyte.Screen,
        selection: tuple[tuple[int, int], tuple[int, int]] | None = None,
    ) -> "Image.Image":
        """Render the entire screen. Returns the full PIL Image."""
        all_rows = set(range(self.rows))
        self.render_dirty(screen, all_rows, selection=selection)
        cursor = self.render_cursor(screen)
        if cursor:
            x, y, _, _, cursor_img = cursor
            self.image.paste(cursor_img, (x, y))
        return self.image
