"""Terminal-to-pixel rendering with VT220 amber-tinted color scheme."""

import logging
import math
import shutil
import subprocess
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont
import pyte
import skia
import wcwidth

log = logging.getLogger(__name__)


# Per-theme 16-color ANSI palettes. Each palette is generated by
# ``oklch.generate_palette`` which picks colors at a constant
# perceived lightness (OKLCH L*) per hue — so every chromatic slot
# looks equally bright to the human eye, and every slot clears WCAG
# AA (4.5:1) contrast against the theme bg. The active palette is
# swapped in place by apply_theme().

# ---------------------------------------------------------------------------
# Phosphor palettes — single-hue per theme. Used by `phosphor` color
# mode (the default). Each palette has all 16 SGR slots but every slot
# is a *brightness* variant of the theme's primary hue — the SGR
# index becomes a luminance cue, not a chroma cue. This is the VT220
# / MDA aesthetic: everything is amber (or green, or grey, or cyan).
#
# Slot 0 ("black") is *near-bg* by design, so it legitimately fails
# the 3:1 contrast floor the other 15 slots clear. See design-color.md.
# ---------------------------------------------------------------------------

# Amber phosphor — preserved from the original vncvt release.
# Invariant: r >= g >= b (warmth).
_AMBER_PHOSPHOR = {
    "black":         (60, 40, 0),
    "red":           (255, 120, 60),
    "green":         (220, 200, 80),
    "brown":         (255, 220, 80),
    "blue":          (230, 180, 60),
    "magenta":       (255, 150, 100),
    "cyan":          (255, 210, 100),
    "white":         (255, 220, 140),
    "brightblack":   (180, 140, 60),
    "brightred":     (255, 160, 100),
    "brightgreen":   (255, 230, 120),
    "brightyellow":  (255, 240, 140),
    "brightblue":    (255, 200, 100),
    "brightmagenta": (255, 190, 140),
    "brightcyan":    (255, 230, 130),
    "brightwhite":   (255, 240, 180),
}

# Green phosphor — preserved. Invariant: g >= {r, b}.
_GREEN_PHOSPHOR = {
    "black":         (0, 30, 10),
    "red":           (180, 255, 180),
    "green":         (60, 255, 120),
    "brown":         (120, 255, 80),
    "blue":          (40, 200, 100),
    "magenta":       (200, 255, 160),
    "cyan":          (100, 255, 180),
    "white":         (200, 255, 200),
    "brightblack":   (40, 180, 90),
    "brightred":     (220, 255, 200),
    "brightgreen":   (160, 255, 200),
    "brightyellow":  (200, 255, 100),
    "brightblue":    (80, 240, 140),
    "brightmagenta": (220, 255, 200),
    "brightcyan":    (180, 255, 220),
    "brightwhite":   (255, 255, 220),
}

# Light phosphor — dark-grey ink-on-paper. Invariant: r == g == b.
# All slots clear WCAG 5:1+ on white bg.
_LIGHT_PHOSPHOR = {
    "black":         (0, 0, 0),
    "red":           (80, 80, 80),
    "green":         (70, 70, 70),
    "brown":         (60, 60, 60),
    "blue":          (50, 50, 50),
    "magenta":       (90, 90, 90),
    "cyan":          (75, 75, 75),
    "white":         (40, 40, 40),
    "brightblack":   (110, 110, 110),
    "brightred":     (65, 65, 65),
    "brightgreen":   (55, 55, 55),
    "brightyellow":  (45, 45, 45),
    "brightblue":    (35, 35, 35),
    "brightmagenta": (80, 80, 80),
    "brightcyan":    (60, 60, 60),
    "brightwhite":   (20, 20, 20),
}

# Dark phosphor — light-grey VT100 aesthetic. Invariant: r == g == b.
# Slot 0 (black) is near-bg by design; other 15 clear WCAG 6:1+.
_DARK_PHOSPHOR = {
    "black":         (20, 20, 20),
    "red":           (180, 180, 180),
    "green":         (190, 190, 190),
    "brown":         (200, 200, 200),
    "blue":          (210, 210, 210),
    "magenta":       (170, 170, 170),
    "cyan":          (185, 185, 185),
    "white":         (220, 220, 220),
    "brightblack":   (140, 140, 140),
    "brightred":     (200, 200, 200),
    "brightgreen":   (215, 215, 215),
    "brightyellow":  (225, 225, 225),
    "brightblue":    (230, 230, 230),
    "brightmagenta": (195, 195, 195),
    "brightcyan":    (210, 210, 210),
    "brightwhite":   (255, 255, 255),
}

# C64 phosphor — blue-purple family (Pepto NTSC palette lineage).
# Invariant: b >= r >= g (cool blue cast).
# Ramp from bg (53,40,121)=#352879 to fg (170,170,255)=#AAAAFF.
_C64_PHOSPHOR = {
    "black":         (53,  40, 121),  # near-bg
    "red":           (71,  60, 141),
    "green":         (82,  73, 155),
    "brown":         (94,  86, 168),
    "blue":          (65,  53, 134),
    "magenta":       (106, 99, 181),
    "cyan":          (117,112, 195),
    "white":         (129,125, 208),
    "brightblack":   (88,  79, 161),
    "brightred":     (141,138, 221),
    "brightgreen":   (152,151, 235),
    "brightyellow":  (158,157, 241),
    "brightblue":    (111,105, 188),
    "brightmagenta": (164,164, 248),
    "brightcyan":    (167,167, 252),
    "brightwhite":   (170,170, 255),
}

# DOS/CGA phosphor — cool-white family on CGA dark blue #0000AA.
# Invariant: b >= r = g (neutral cool tint toward blue).
# Ramp from bg (0,0,170)=#0000AA to fg (255,255,255)=#FFFFFF.
_DOS_PHOSPHOR = {
    "black":         (0,   0,  170),  # near-bg
    "red":           (26,  26, 179),
    "green":         (51,  51, 187),
    "brown":         (77,  77, 196),
    "blue":          (13,  13, 174),
    "magenta":       (102,102, 204),
    "cyan":          (128,128, 213),
    "white":         (153,153, 221),
    "brightblack":   (64,  64, 191),
    "brightred":     (179,179, 230),
    "brightgreen":   (204,204, 238),
    "brightyellow":  (217,217, 242),
    "brightblue":    (115,115, 208),
    "brightmagenta": (230,230, 247),
    "brightcyan":    (242,242, 251),
    "brightwhite":   (255,255, 255),
}

# Atari GTIA phosphor — warm orange family (GTIA hue-2 ramp, Lospec).
# Invariant: r >= g >= b (warm cast, mirrors amber).
# Ramp from bg (0,0,0)=#000000 to fg (253,193,112)=#FDC170.
_ATARI_PHOSPHOR = {
    "black":         (0,   0,   0),   # near-bg
    "red":           (51,  39,  22),
    "green":         (76,  58,  34),
    "brown":         (101, 77,  45),
    "blue":          (25,  19,  11),
    "magenta":       (127, 97,  56),
    "cyan":          (152,116,  67),
    "white":         (177,135,  78),
    "brightblack":   (63,  48,  28),
    "brightred":     (202,154,  90),
    "brightgreen":   (215,164,  95),
    "brightyellow":  (228,174, 101),
    "brightblue":    (89,  68,  39),
    "brightmagenta": (240,183, 106),
    "brightcyan":    (247,188, 109),
    "brightwhite":   (253,193, 112),
}

# Active palette — apply_theme() replaces this dict in place so any
# code holding a reference (including the 256-color builders below)
# sees the new colors. AMBER_COLORS is kept as a back-compat alias
# and points at the *phosphor* palette since that's the default mode.
AMBER_COLORS = dict(_AMBER_PHOSPHOR)

# pyte uses these names for the 8 basic colors
_PYTE_COLOR_NAMES = [
    "black", "red", "green", "brown", "blue", "magenta", "cyan", "white",
]

# Chars that should NEVER get an underline drawn under them, even if
# the cell has underscore=True. Covers ASCII space, NBSP, and the
# whole Unicode box-drawing block so separator rows don't produce a
# visible dark band.
_NO_UNDERLINE = frozenset(
    [" ", "\xa0"] + [chr(c) for c in range(0x2500, 0x2580)]
)

# Theme palettes. The active one is installed into the module-level
# DEFAULT_BG / DEFAULT_FG / BOLD_FG / CURSOR_COLOR constants by
# ``apply_theme()``; modules like test_padding.py that import
# DEFAULT_BG directly pick up whatever the current theme set.
THEMES: dict[str, dict] = {
    # Each theme has one 16-slot palette: `ansi_phosphor` (single-hue
    # ramp for `phosphor` mode). In `true-color` mode the standard
    # xterm 256-color palette is used instead — no per-theme variant.
    "amber": {
        "bg":            (0, 0, 0),
        "fg":            (255, 190, 80),   # 12.73:1
        "bold":          (255, 220, 120),  # ~14.5:1
        "cursor":        (255, 190, 80),
        "ansi_phosphor": _AMBER_PHOSPHOR,
    },
    "light": {  # black on white — 21.00:1 (WCAG max)
        "bg":            (255, 255, 255),
        "fg":            (0, 0, 0),
        "bold":          (0, 0, 0),
        "cursor":        (0, 0, 0),
        "ansi_phosphor": _LIGHT_PHOSPHOR,
    },
    "dark": {  # white on black — 21.00:1 (WCAG max)
        "bg":            (0, 0, 0),
        "fg":            (255, 255, 255),
        "bold":          (255, 255, 255),
        "cursor":        (255, 255, 255),
        "ansi_phosphor": _DARK_PHOSPHOR,
    },
    "green": {  # P31 phosphor green — 16.31:1
        "bg":            (0, 0, 0),
        "fg":            (120, 255, 120),
        "bold":          (180, 255, 180),
        "cursor":        (120, 255, 120),
        "ansi_phosphor": _GREEN_PHOSPHOR,
    },
    "c64": {  # Commodore 64 BASIC — Pepto NTSC palette
        "bg":            (53, 40, 121),    # #352879
        "fg":            (170, 170, 255),  # #AAAAFF  4.94:1 AA
        "bold":          (200, 200, 255),  # #C8C8FF
        "cursor":        (170, 170, 255),
        "ansi_phosphor": _C64_PHOSPHOR,
    },
    "dos": {  # CGA dark blue — WordPerfect / Norton Commander
        "bg":            (0, 0, 170),      # #0000AA
        "fg":            (255, 255, 255),  # #FFFFFF  16.94:1 AAA
        "bold":          (255, 255, 85),   # #FFFF55  CGA bright yellow
        "cursor":        (255, 255, 255),
        "ansi_phosphor": _DOS_PHOSPHOR,
    },
    "atari": {  # Atari 8-bit GTIA hue-2 lum-6 ($2C)
        "bg":            (0, 0, 0),
        "fg":            (253, 193, 112),  # #FDC170  13.40:1 AAA
        "bold":          (255, 220, 160),  # #FFDCA0
        "cursor":        (253, 193, 112),
        "ansi_phosphor": _ATARI_PHOSPHOR,
    },
}

DEFAULT_BG = THEMES["amber"]["bg"]
DEFAULT_FG = THEMES["amber"]["fg"]
BOLD_FG = THEMES["amber"]["bold"]
CURSOR_COLOR = THEMES["amber"]["cursor"]


def apply_theme(name: str) -> None:
    """Install one of the THEMES palettes as the module-level defaults.

    Call before constructing any TerminalRenderer — the render path
    reads DEFAULT_BG / DEFAULT_FG / BOLD_FG / CURSOR_COLOR at draw
    time, so swapping them here is enough for a theme change. The
    256-slot phosphor palette is also rebuilt so _resolve_color can
    look up integer ANSI indices in phosphor mode.
    """
    if name not in THEMES:
        raise ValueError(
            f"unknown theme {name!r}; expected one of {sorted(THEMES)}"
        )
    global DEFAULT_BG, DEFAULT_FG, BOLD_FG, CURSOR_COLOR
    global _PALETTE_PHOSPHOR
    palette = THEMES[name]
    DEFAULT_BG = palette["bg"]
    DEFAULT_FG = palette["fg"]
    BOLD_FG = palette["bold"]
    CURSOR_COLOR = palette["cursor"]
    _PALETTE_PHOSPHOR = _build_256_phosphor(palette["ansi_phosphor"])
    AMBER_COLORS.clear()
    AMBER_COLORS.update(palette["ansi_phosphor"])

_VENDORED_FONT_DIR = Path(__file__).parent / "fonts"

FONT_SEARCH_PATHS = [
    # macOS: SF Mono Regular (system font). With Skia's subpixel AA
    # and LCD filtering, this matches what macOS Terminal.app renders.
    "/System/Library/Fonts/SFNSMono.ttf",
    # macOS fallback
    "/System/Library/Fonts/Menlo.ttc",
    # Linux fallbacks
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf",
    "/usr/share/fonts/truetype/freefont/FreeMono.ttf",
    "/usr/share/fonts/TTF/DejaVuSansMono.ttf",
    "/usr/share/fonts/dejavu-sans-mono-fonts/DejaVuSansMono.ttf",
    # Vendored Terminus TTF is kept as the ultimate fallback for
    # environments without any monospace font installed.
    str(_VENDORED_FONT_DIR / "TerminusTTF-4.49.3.ttf"),
]

BOLD_FONT_SEARCH_PATHS = [
    "/System/Library/Fonts/SFNSMono.ttf",  # has an embedded Bold face
    "/System/Library/Fonts/Menlo.ttc",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf",
    "/usr/share/fonts/truetype/freefont/FreeMonoBold.ttf",
    "/usr/share/fonts/TTF/DejaVuSansMono-Bold.ttf",
    str(_VENDORED_FONT_DIR / "TerminusTTF-Bold-4.49.3.ttf"),
]


def _find_font(paths: list[str]) -> str | None:
    for path in paths:
        if Path(path).exists():
            return path
    if shutil.which("fc-match"):
        try:
            out = subprocess.check_output(
                ["fc-match", "-f", "%{file}", "monospace"], text=True
            ).strip()
            if Path(out).exists():
                return out
        except subprocess.SubprocessError:
            pass
    return None


# Phosphor palette builder. One table is built per theme (phosphor
# mode only). In true-color mode _STANDARD_PALETTE_256 is used instead.
_BRIGHT_MAP = {
    "black": "brightblack", "red": "brightred", "green": "brightgreen",
    "brown": "brightyellow", "blue": "brightblue", "magenta": "brightmagenta",
    "cyan": "brightcyan", "white": "brightwhite",
}



def _build_256_phosphor(
    ansi16: dict[str, tuple[int, int, int]],
) -> list[tuple[int, int, int]]:
    """Build a phosphor-mode 256-slot palette.

    Slots 0-15: verbatim phosphor entries (already single-hue).
    Slots 16-231: xterm 6x6x6 cube collapsed onto the single-hue
      brightness ramp by mapping each entry's perceived luminance to
      the palette's black→brightwhite axis. RGB blending (as used by
      ``_build_256_from_ansi16``) can't be used here because high-B
      xterm cube entries would keep enough blue to be blue-dominant
      after the blend, violating the single-hue invariant.
    Slots 232-255: linear interpolation on the black→brightwhite ramp
      (same as ``_build_256_from_ansi16``).
    """
    palette: list[tuple[int, int, int]] = []
    for name in _PYTE_COLOR_NAMES:
        palette.append(ansi16[name])
    for name in _PYTE_COLOR_NAMES:
        palette.append(ansi16[_BRIGHT_MAP[name]])

    black = ansi16["black"]
    white = ansi16["brightwhite"]

    def _lum_to_ramp(r: int, g: int, b: int) -> tuple[int, int, int]:
        """Map sRGB luminance of (r,g,b) onto the black→white ramp."""
        lin = lambda v: (v / 255.0 / 12.92 if v / 255.0 <= 0.04045
                         else ((v / 255.0 + 0.055) / 1.055) ** 2.4)
        lum = 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b)
        # Gamma lift (matches _apply_oklab_ramp's 0.4 exponent) so
        # mid-luminance inputs land in the readable midrange rather
        # than clustering near black.
        t = min(1.0, max(0.0, lum)) ** 0.4
        return (
            int(black[0] + (white[0] - black[0]) * t),
            int(black[1] + (white[1] - black[1]) * t),
            int(black[2] + (white[2] - black[2]) * t),
        )

    levels = [0, 0x5f, 0x87, 0xaf, 0xd7, 0xff]
    for r in levels:
        for g in levels:
            for b in levels:
                palette.append(_lum_to_ramp(r, g, b))

    for i in range(24):
        t = i / 23.0
        palette.append((
            int(black[0] + (white[0] - black[0]) * t),
            int(black[1] + (white[1] - black[1]) * t),
            int(black[2] + (white[2] - black[2]) * t),
        ))
    return palette


# Module-level phosphor palette. apply_theme() rebuilds this whenever
# the theme changes. true-color mode uses _STANDARD_PALETTE_256 instead.
_PALETTE_PHOSPHOR = _build_256_phosphor(_AMBER_PHOSPHOR)


# Standard xterm 256-color palette — NOT theme-tinted. Used by
# true-color mode so TUIs emitting ANSI indices render in their
# native xterm colors instead of the theme's OKLCH palette.
_STANDARD_ANSI_16 = [
    (0, 0, 0), (205, 0, 0), (0, 205, 0), (205, 205, 0),
    (0, 0, 238), (205, 0, 205), (0, 205, 205), (229, 229, 229),
    (127, 127, 127), (255, 0, 0), (0, 255, 0), (255, 255, 0),
    (92, 92, 255), (255, 0, 255), (0, 255, 255), (255, 255, 255),
]


def _build_standard_256() -> list[tuple[int, int, int]]:
    palette = list(_STANDARD_ANSI_16)
    levels = [0, 95, 135, 175, 215, 255]
    for r in levels:
        for g in levels:
            for b in levels:
                palette.append((r, g, b))
    for i in range(24):
        v = 8 + i * 10
        palette.append((v, v, v))
    return palette


_STANDARD_PALETTE_256 = _build_standard_256()



def _cell_in_selection(
    col: int,
    row: int,
    sel: tuple[tuple[int, int], tuple[int, int]] | None,
) -> bool:
    """Return True if (col, row) lies within the normalized selection."""
    if sel is None:
        return False
    (sc, sr), (ec, er) = sel
    if row < sr or row > er:
        return False
    if row == sr and row == er:
        return sc <= col <= ec
    if row == sr:
        return col >= sc
    if row == er:
        return col <= ec
    return True


class TerminalRenderer:
    """Renders a pyte Screen to an RGBX pixel buffer with amber-tinted colors."""

    # Overscan compensation: extra pixels of background around the
    # cell grid, like a CRT's overscan region. Mostly cosmetic — it
    # keeps the first column of text from hugging the screen edge.
    PADDING = 5

    def __init__(
        self,
        cols: int = 80,
        rows: int = 24,
        font_path: str | None = None,
        font_size: int = 16,
        line_height: float = 1.0,
        contrast: str = "normal",
        color_mode: str = "phosphor",
    ):
        self.cols = cols
        self.rows = rows
        self.padding = self.PADDING
        self.contrast = contrast
        self.color_mode = color_mode
        self.line_height = line_height

        # Load fonts
        if font_path is None:
            font_path = _find_font(FONT_SEARCH_PATHS)
        if font_path is None:
            raise RuntimeError(
                "No monospace font found. Install dejavu-sans-mono or use --font."
            )
        # Stash resolved font path + size so Phase 2 SET-UP mode can
        # rebuild this renderer without guessing (Pillow's ImageFont
        # doesn't expose the path portably across versions).
        self._font_path = font_path
        self.font_size = font_size
        self.font = ImageFont.truetype(font_path, font_size)

        bold_path = _find_font(BOLD_FONT_SEARCH_PATHS)
        self.font_bold = (
            ImageFont.truetype(bold_path, font_size) if bold_path else self.font
        )

        # Skia fonts for actual glyph rasterization. Pillow's fonts
        # above are kept for getlength() / getmetrics() measurement
        # only — Skia does the drawing so we get subpixel positioning,
        # LCD filtering, and stem darkening that Pillow+FreeType doesn't
        # expose.
        self._skia_typeface = skia.Typeface.MakeFromFile(font_path)
        self._skia_typeface_bold = (
            skia.Typeface.MakeFromFile(bold_path) if bold_path
            else self._skia_typeface
        )
        self._skia_font = skia.Font(self._skia_typeface, font_size)
        self._skia_font_bold = skia.Font(self._skia_typeface_bold, font_size)

        # Font fallback chain. When a codepoint's glyph is missing from
        # the primary typeface (Hangul / CJK / emoji), we walk this list
        # and pick the first entry whose unicharToGlyph returns non-zero.
        # Order matters: we want SF Mono (or whatever --font was set)
        # to win for Latin, Sarasa Mono K for CJK, and Apple Color
        # Emoji for pictographic codepoints.
        self._skia_fallback_fonts: list[skia.Font] = [self._skia_font]
        self._skia_fallback_fonts_bold: list[skia.Font] = [self._skia_font_bold]
        # Per-font "is color bitmap" flag so _draw_glyph can avoid
        # tinting emoji via Paint.setColor.
        self._skia_fallback_is_color: list[bool] = [False]
        self._skia_fallback_is_color_bold: list[bool] = [False]

        sarasa_reg = _VENDORED_FONT_DIR / "SarasaMonoK-Regular.ttf"
        sarasa_bold = _VENDORED_FONT_DIR / "SarasaMonoK-Bold.ttf"
        if sarasa_reg.is_file():
            tf = skia.Typeface.MakeFromFile(str(sarasa_reg))
            if tf is not None:
                self._skia_fallback_fonts.append(skia.Font(tf, font_size))
                self._skia_fallback_is_color.append(False)
        if sarasa_bold.is_file():
            tf = skia.Typeface.MakeFromFile(str(sarasa_bold))
            if tf is not None:
                self._skia_fallback_fonts_bold.append(skia.Font(tf, font_size))
                self._skia_fallback_is_color_bold.append(False)

        _emoji_candidates = [
            # macOS system font (Apple Color Emoji — sbix color bitmaps)
            Path("/System/Library/Fonts/Apple Color Emoji.ttc"),
            # Vendored fallback for Linux CI and other non-macOS platforms
            # (Noto Color Emoji — CBDT/CBLC color bitmaps, OFL 1.1)
            _VENDORED_FONT_DIR / "NotoColorEmoji.ttf",
        ]
        for _emoji_path in _emoji_candidates:
            if _emoji_path.is_file():
                tf = skia.Typeface.MakeFromFile(str(_emoji_path))
                if tf is not None:
                    emoji_font = skia.Font(tf, font_size)
                    self._skia_fallback_fonts.append(emoji_font)
                    self._skia_fallback_is_color.append(True)
                    # Bold reuses the same emoji font — color emoji has no
                    # weight axis.
                    self._skia_fallback_fonts_bold.append(emoji_font)
                    self._skia_fallback_is_color_bold.append(True)
                    break

        # Apply shared rasterization flags to every fallback font.
        for f in (
            *self._skia_fallback_fonts,
            *self._skia_fallback_fonts_bold,
        ):
            f.setSubpixel(True)
            # Grayscale AA (not LCD subpixel) — amber-on-black has no
            # blue channel transition, so subpixel rendering produces
            # red/green fringes that hurt perceived crispness. Plain
            # gray AA stays out of the way.
            f.setEdging(skia.Font.Edging.kAntiAlias)
            # In high-contrast mode, drop hinting to kNone so glyph
            # outlines are rasterized without pixel-snap; the resulting
            # strokes are thicker (1.5-2 px wide instead of hard-snapped
            # 1 px) and look noticeably brighter at small sizes.
            f.setHinting(
                skia.FontHinting.kNone if contrast == "high"
                else skia.FontHinting.kFull
            )
            # Let SF Mono's native TrueType hints drive — they're
            # hand-tuned by Apple and beat Skia's autohinter.
            f.setForceAutoHinting(False)
            f.setLinearMetrics(False)
            f.setBaselineSnap(True)

        # Baseline offset: Pillow's draw.text anchors glyphs at the
        # top-left; Skia's drawString anchors at the baseline. Stash
        # the font's ascent so the call site can pass the baseline
        # y-coordinate.
        skia_metrics = self._skia_font.getMetrics()
        self._skia_baseline = -skia_metrics.fAscent

        # Measure character cell using advance width, not ink bbox.
        # getlength() returns the horizontal advance — the correct metric for
        # grid layout in a monospace font. Use math.ceil so we always
        # round UP; int(round()) can undersize the cell by ~0.5 px for
        # fonts whose advance is fractional (SF Mono at 13pt → 7.8,
        # rounded to 8, which leaves a sub-pixel gap every ~6 glyphs).
        self.cell_width = math.ceil(self.font.getlength("M"))
        ascent, descent = self.font.getmetrics()
        font_cell_h = ascent + descent
        self.cell_height = max(1, math.ceil(font_cell_h * self.line_height))
        self._x_offset = 0
        # Vertically center the glyph inside the expanded cell when
        # line_height > 1.0 so the extra space is shared above/below.
        self._y_offset = (self.cell_height - font_cell_h) // 2
        self._skia_baseline += self._y_offset

        # Warn if bold font has a different advance (would cause grid drift).
        if self.font_bold is not self.font:
            bold_adv = int(round(self.font_bold.getlength("M")))
            if bold_adv != self.cell_width:
                log.warning(
                    "Bold font advance (%d) != regular (%d); bold glyphs "
                    "will be clipped to the regular cell width",
                    bold_adv, self.cell_width,
                )

        self.width = cols * self.cell_width + 2 * self.padding
        self.height = rows * self.cell_height + 2 * self.padding

        # Create framebuffer image (padded by DEFAULT_BG on all sides).
        self.image = Image.new("RGBX", (self.width, self.height), DEFAULT_BG)
        self._prev_cursor = (-1, -1)

    def _find_font_for_char(
        self, ch: str, bold: bool,
    ) -> tuple["skia.Font", bool]:
        """Pick the first fallback font that has a glyph for ``ch``.

        Returns ``(font, is_color)`` where is_color signals that the
        font renders via color bitmaps (Apple Color Emoji) and the
        caller must not apply a Paint color — that would tint the
        sbix bitmap.
        """
        if bold:
            fonts = self._skia_fallback_fonts_bold
            color_flags = self._skia_fallback_is_color_bold
        else:
            fonts = self._skia_fallback_fonts
            color_flags = self._skia_fallback_is_color
        code = ord(ch[0])
        for font, is_color in zip(fonts, color_flags):
            if font.unicharToGlyph(code):
                return font, is_color
        # Fall back to the primary so the renderer at least draws
        # .notdef instead of silently skipping.
        return fonts[0], color_flags[0]

    def _draw_glyph(
        self,
        ch: str,
        bold: bool,
        x: int,
        y: int,
        fg: tuple[int, int, int],
        bg: tuple[int, int, int],
        cell_w: int,
    ) -> None:
        """Rasterize one glyph via Skia and paste into self.image.

        Skia gives us subpixel positioning, LCD filtering, and stem
        darkening that Pillow+FreeType doesn't expose. The tradeoff
        is one tiny offscreen surface per glyph — acceptable for
        dirty-row rendering at ~80 chars/row × 30 rows.
        """
        w = cell_w
        h = self.cell_height
        surface = skia.Surface.MakeRasterN32Premul(w, h)
        canvas = surface.getCanvas()
        canvas.clear(skia.ColorSetRGB(*bg))
        font, is_color = self._find_font_for_char(ch, bold=bold)
        paint = skia.Paint(AntiAlias=True)
        if not is_color or self.color_mode == "phosphor":
            # Color-bitmap fonts (Apple Color Emoji / Noto Color Emoji)
            # carry their own sbix/CBDT pixels; applying Paint.setColor
            # tints the bitmap to the fg color, destroying the art. The
            # exception is phosphor mode, which collapses every hue to the
            # theme's single-hue ramp — emoji must be tinted amber too so
            # no blue-dominant pixels leak through from the color bitmaps.
            paint.setColor(skia.ColorSetRGB(*fg))
        canvas.drawString(ch, 0, self._skia_baseline, font, paint)
        if not is_color:
            # Embolden via repeated draws at sub-pixel offsets.
            # Each extra draw thickens strokes without the jaggies of
            # 1-bit AA. Skipped for color bitmap emoji (would smear
            # the sbix bitmap).
            if self.contrast == "high":
                # +1 horizontal draw → strokes are ~1.5-2 px wide
                canvas.drawString(ch, 1, self._skia_baseline, font, paint)
            elif self.contrast == "max":
                # Horizontal + diagonal half-step → thicker than
                # "high" without the blocky smear of a 4-corner
                # draw. Keeps curve outlines smooth.
                canvas.drawString(ch, 1, self._skia_baseline, font, paint)
                canvas.drawString(
                    ch, 0.5, self._skia_baseline + 0.5, font, paint,
                )
        # Snapshot -> RGBA bytes -> paste into self.image.
        # Skia's native N32 colour type is BGRA on Linux (little-endian
        # x86) and RGBA on macOS arm64. To get a consistent channel order
        # we request kRGBA_8888_SkColorType explicitly; Skia performs the
        # BGRA→RGBA swizzle during readPixels if needed.
        img_info = skia.ImageInfo.Make(
            w, h,
            skia.kRGBA_8888_ColorType,
            skia.kPremul_AlphaType,
        )
        buf = bytearray(w * h * 4)
        surface.readPixels(img_info, buf, w * 4, 0, 0)
        tile = Image.frombytes("RGBA", (w, h), bytes(buf))
        self.image.paste(tile, (x, y))

    def resize(self, cols: int, rows: int) -> None:
        """Resize the framebuffer to new terminal dimensions."""
        self.cols = cols
        self.rows = rows
        self.width = cols * self.cell_width + 2 * self.padding
        self.height = rows * self.cell_height + 2 * self.padding
        self.image = Image.new("RGBX", (self.width, self.height), DEFAULT_BG)
        self._prev_cursor = (-1, -1)

    def _resolve_color(
        self,
        color: str,
        bold: bool = False,
        is_bg: bool = False,
        cell_bg: tuple[int, int, int] | None = None,
    ) -> tuple[int, int, int]:
        """Map a pyte color value to an amber-tinted RGB tuple."""
        if color == "default" or color is None:
            if is_bg:
                return DEFAULT_BG
            return BOLD_FG if bold else DEFAULT_FG

        # Named color
        if color in AMBER_COLORS:
            if bold and not is_bg and not color.startswith("bright"):
                # "brown" promotes to "brightyellow" per standard ANSI
                bright_name = "brightyellow" if color == "brown" else ("bright" + color)
                if bright_name in AMBER_COLORS:
                    return AMBER_COLORS[bright_name]
            return AMBER_COLORS[color]

        # Integer index (ANSI 0–255)
        if isinstance(color, int) or (
            isinstance(color, str) and len(color) <= 3 and color.isdigit()
        ):
            idx = int(color)
            if 0 <= idx < 256:
                if self.color_mode == "true-color":
                    return _STANDARD_PALETTE_256[idx]
                # phosphor (default): every SGR index collapses to a
                # brightness variant of the theme's single hue.
                return _PALETTE_PHOSPHOR[idx]

        # 6-char hex string (truecolor). fg is routed through the
        # theme's bg→fg OKLab ramp with a gamma-0.4 lift so dim greys
        # like Claude Code's #808080 hints stay WCAG-AA readable.
        # bg passes through raw in true-color mode (preserves TUI
        # backdrop intent); phosphor mode collapses it to the ramp.
        if isinstance(color, str) and len(color) == 6:
            try:
                r = int(color[0:2], 16)
                g = int(color[2:4], 16)
                b = int(color[4:6], 16)
                ramp_rgb = self._apply_oklab_ramp(
                    r, g, b, is_bg=is_bg, cell_bg=cell_bg,
                )
                if self.color_mode == "true-color":
                    return (r, g, b) if is_bg else ramp_rgb
                return ramp_rgb
            except ValueError:
                pass

        return DEFAULT_FG

    def _apply_oklab_ramp(
        self,
        r: int,
        g: int,
        b: int,
        is_bg: bool,
        cell_bg: tuple[int, int, int] | None,
    ) -> tuple[int, int, int]:
        """Map a raw truecolor input onto the theme's bg→fg OKLab ramp.

        Returns the ramp-mapped RGB regardless of mode; callers decide
        whether to use it raw, blended, or as a full replacement.

        Preserves the orientation flip, cell_bg-aware reference frame,
        L_eff floor, and gamma 0.4 lift introduced earlier so Claude
        Code's mid-grey hint colors clear WCAG AA on every theme.
        """
        from .oklch import srgb_to_oklab
        L, _, _ = srgb_to_oklab(r, g, b)
        # Choose the lift's reference frame. If the caller told us the
        # cell's actual bg (via cell_bg), use that — fg should always be
        # pushed *away* from the bg it will be painted against,
        # regardless of theme defaults. Falling back to DEFAULT_BG /
        # DEFAULT_FG when cell_bg is unknown preserves legacy behavior.
        if cell_bg is not None:
            bg_L, _, _ = srgb_to_oklab(*cell_bg)
            if bg_L >= 0.5:
                # Light cell bg: push fg toward black so the darkest
                # input intent (L=0) lands on black.
                ref_bg = (255, 255, 255)
                ref_fg = (0, 0, 0)
            else:
                ref_bg = (0, 0, 0)
                ref_fg = (255, 255, 255)
            ref_bg_L = 1.0 if bg_L >= 0.5 else 0.0
            ref_fg_L = 0.0 if bg_L >= 0.5 else 1.0
        else:
            ref_bg = DEFAULT_BG
            ref_fg = DEFAULT_FG
            ref_bg_L, _, _ = srgb_to_oklab(*DEFAULT_BG)
            ref_fg_L, _, _ = srgb_to_oklab(*DEFAULT_FG)
        # The lift parameterizes the input on a bg→fg perceptual ramp.
        # On dark-on-light orientations (ref_bg brighter than ref_fg),
        # L=0 is the user's darkest intent and should map to ref_fg
        # (black), not ref_bg (white). Flip the parameter so the ramp
        # always goes "user intent low → bg, user intent high → fg"
        # relative to the chosen orientation.
        L_eff = L if ref_fg_L >= ref_bg_L else (1.0 - L)
        # Floor L_eff so an input that lands on (or very near) the bg
        # pole still gets enough lift to escape it. Rescues the
        # "fg=#000000 on a dark cell bg" case where the user's literal
        # intent is invisible — we honor the neutrality (still grey)
        # but force enough delta from the bg to clear ~9:1.
        L_eff = max(L_eff, 0.5)
        # Clamp L into [0, 1] then apply gamma lift. The 0.4 exponent
        # was tuned against Claude Code's actual grey inputs (#808080,
        # #949494, #d78787) to clear 4.5:1 on every built-in theme bg.
        t = max(0.0, min(1.0, L_eff)) ** 0.4
        bg_r, bg_g, bg_b = ref_bg
        fg_r, fg_g, fg_b = ref_fg
        return (
            int(bg_r + (fg_r - bg_r) * t),
            int(bg_g + (fg_g - bg_g) * t),
            int(bg_b + (fg_b - bg_b) * t),
        )

    def render_dirty(
        self,
        screen: pyte.Screen,
        dirty_rows: set[int],
        selection: tuple[tuple[int, int], tuple[int, int]] | None = None,
    ) -> list[tuple[int, int, int, int, "Image.Image"]]:
        """Re-render dirty rows. Returns list of (x, y, w, h, PIL.Image) rectangles.

        If `selection` is given as ``((start_col, start_row), (end_col, end_row))``
        in reading order, cells inside the range are drawn with inverted
        foreground/background colors to indicate highlight.
        """
        if not dirty_rows:
            return []

        draw = ImageDraw.Draw(self.image)
        rects = []

        pad = self.padding
        inner_w = self.cols * self.cell_width

        for row in sorted(dirty_rows):
            if row >= self.rows:
                continue
            y = row * self.cell_height + pad

            # Clear the cell-grid area for this row (leave side padding alone).
            draw.rectangle(
                [pad, y, pad + inner_w - 1, y + self.cell_height - 1],
                fill=DEFAULT_BG,
            )

            line = screen.buffer[row]
            skip_next = 0
            for col in range(self.cols):
                if skip_next:
                    skip_next -= 1
                    continue

                char = line[col]
                x = col * self.cell_width + pad
                ch = char.data

                bg = self._resolve_color(char.bg, False, is_bg=True)
                fg = self._resolve_color(
                    char.fg, char.bold, is_bg=False, cell_bg=bg,
                )

                if char.reverse:
                    fg, bg = bg, fg

                # Selection highlight: invert after reverse handling so a
                # reverse-video cell inside a selection returns to normal.
                if _cell_in_selection(col, row, selection):
                    fg, bg = bg, fg

                # Determine cell span via wcwidth.
                #   2  -> double-wide (CJK, some emoji)
                #   1  -> normal
                #   0  -> combining mark (overlay onto previous cell)
                #  -1  -> control/unassigned (treat as 1)
                w = wcwidth.wcwidth(ch) if ch else 1
                cells = 2 if w == 2 else 1
                cell_px = self.cell_width * cells

                # Combining mark: overlay on previous cell. For now
                # we just draw it over the previous cell's bg — Skia
                # doesn't support stacking marks trivially. Acceptable
                # since combining marks are rare in terminal output.
                if w == 0 and col > 0 and ch:
                    prev_x = (col - 1) * self.cell_width + pad
                    self._draw_glyph(
                        ch, char.bold, prev_x, y, fg, DEFAULT_BG,
                        self.cell_width,
                    )
                    continue

                # Draw the cell: background + glyph in one Skia pass.
                # _draw_glyph fills bg first then draws the glyph, so
                # we don't need a separate rectangle clear.
                if ch and ch != " ":
                    self._draw_glyph(
                        ch, char.bold, x, y, fg, bg, cell_px,
                    )
                elif bg != DEFAULT_BG:
                    # Empty cell with a non-default background.
                    draw.rectangle(
                        [x, y, x + cell_px - 1, y + self.cell_height - 1],
                        fill=bg,
                    )

                # Underline — skip on whitespace and box-drawing cells.
                # Claude Code (and some other TUIs) set the underscore
                # attribute on whole rows of separator characters
                # (`─`, spaces). Rendering a full-width underline bar
                # under those produces a visible dark horizontal valley.
                # For real text (URLs, prompts) the underline is still
                # drawn in the cell's fg color.
                if char.underscore and ch and ch not in _NO_UNDERLINE:
                    ul_y = y + self.cell_height - 2
                    draw.line(
                        [x, ul_y, x + cell_px - 1, ul_y], fill=fg,
                    )

                if cells == 2:
                    skip_next = 1

            # Return a crop view of the row (inner area only). Skipping
            # the side padding saves a few bytes per row and keeps the
            # update bounded to cells that actually changed.
            row_img = self.image.crop(
                (pad, y, pad + inner_w, y + self.cell_height)
            )
            rects.append((pad, y, inner_w, self.cell_height, row_img))

        return rects

    def render_cursor(
        self, screen: pyte.Screen
    ) -> tuple[int, int, int, int, "Image.Image"] | None:
        """Render cursor block. Returns (x, y, w, h, PIL.Image) or None."""
        cx, cy = screen.cursor.x, screen.cursor.y
        if cx >= self.cols or cy >= self.rows:
            return None

        char = screen.buffer[cy][cx]
        ch = char.data
        w = wcwidth.wcwidth(ch) if ch else 1
        cells = 2 if w == 2 else 1
        cell_px = self.cell_width * cells

        x = cx * self.cell_width + self.padding
        y = cy * self.cell_height + self.padding

        # Draw cursor as a filled block with inverted colors.
        cursor_img = self.image.crop(
            (x, y, x + cell_px, y + self.cell_height)
        ).copy()
        draw = ImageDraw.Draw(cursor_img)
        draw.rectangle(
            [0, 0, cell_px - 1, self.cell_height - 1],
            fill=CURSOR_COLOR,
        )

        # Redraw character under cursor with inverted color.
        if ch and ch != " ":
            draw.text(
                (self._x_offset, self._y_offset),
                ch, font=self.font, fill=DEFAULT_BG,
            )

        self._prev_cursor = (cx, cy)
        return (x, y, cell_px, self.cell_height, cursor_img)

    def full_render(
        self,
        screen: pyte.Screen,
        selection: tuple[tuple[int, int], tuple[int, int]] | None = None,
    ) -> "Image.Image":
        """Render the entire screen. Returns the full PIL Image."""
        all_rows = set(range(self.rows))
        self.render_dirty(screen, all_rows, selection=selection)
        cursor = self.render_cursor(screen)
        if cursor:
            x, y, _, _, cursor_img = cursor
            self.image.paste(cursor_img, (x, y))
        return self.image
